// DRAWER
export const OPEN_DRAWER = 'OPEN_DRAWER'
// DIALOG
export const OPEN_DIALOG = 'OPEN_DIALOG'
// Components
export const OPEN_COMPONENT = 'OPEN_COMPONENT'
export const OPEN_FORM = 'OPEN_FORM'

export const STEPPER_PRODUCT = 'STEPPER_PRODUCT'
export const STEPPER_PLACES = 'STEPPER_PLACES'

// Product Types
const PRODUCT_NAME = 'PRODUCT_NAME'
const PRODUCT_BARCODE = 'PRODUCT_BARCODE'
const PRODUCT_THUMBNAIL = 'PRODUCT_THUMBNAIL'
const PRODUCT_DETAIL = 'PRODUCT_DETAIL'
const PRODUCT_PRICE = 'PRODUCT_PRICE'
const PRODUCT_FIRSTIMAGE = 'PRODUCT_FIRSTIMAGE'
const PRODUCT_SECONDIMAGE = 'PRODUCT_SECONDIMAGE'
const PRODUCT_THIRDIMAGE = 'PRODUCT_THIRDIMAGE'
// Place Types
const PLACE_NAME = 'PLACE_NAME'
const PLACE_LAT = 'PLACE_LAT'
const PLACE_LON = 'PLACE_LON'
const PLACE_DES = 'PLACE_DES'
const PLACE_FIRSTIMAGE = 'PLACE_FIRSTIMAGE'
const PLACE_SECONDIMAGE = 'PLACE_SECONDIMAGE'
const PLACE_THIRDIMAGE = 'PLACE_THIRDIMAGE'
// Categories Types
const CATEGORIES_NAME = 'CATEGORIES_NAME'
// Admin Types
const ADMIN_EMAIL = 'ADMIN_EMAIL'
const ADMIN_PASSWORD = 'ADMIN_PASSWORD'
const ADMIN_FIRSTNAME = 'ADMIN_FIRSTNAME'
const ADMIN_LASTNAME = 'ADMIN_LASTNAME'
// News Types
const NEWS_TITLE = 'NEWS_TITLE'
const NEWS_DES = 'NEWS_DES'
const NEWS_THUMBNAIL = 'NEWS_THUMBNAIL'
const NEWS_TYPE = 'NEWS_TYPE'
const NEWS_REF = 'NEWS_REF'
const NEWS_FIRSTIMAGE = 'NEWS_FIRSTIMAGE'
const NEWS_SECONDIMAGE = 'NEWS_SECONDIMAGE'
const NEWS_THIRDIMAGE = 'NEWS_THIRDIMAGE'


export {

    // PRODUCT FORM.
    PRODUCT_NAME,
    PRODUCT_BARCODE,
    PRODUCT_THUMBNAIL,
    PRODUCT_DETAIL,
    PRODUCT_PRICE,
    PRODUCT_FIRSTIMAGE,
    PRODUCT_SECONDIMAGE,
    PRODUCT_THIRDIMAGE,
    // PLACE FORM.
    PLACE_NAME,
    PLACE_LAT,
    PLACE_LON,
    PLACE_DES,
    PLACE_FIRSTIMAGE,
    PLACE_SECONDIMAGE,
    PLACE_THIRDIMAGE,
    // CATEGORIES FORM.
    CATEGORIES_NAME,
    // ADMIN FORM.
    ADMIN_EMAIL,
    ADMIN_PASSWORD,
    ADMIN_FIRSTNAME,
    ADMIN_LASTNAME,
    // NEWS FORM.
    NEWS_TITLE,
    NEWS_DES,
    NEWS_THUMBNAIL,
    NEWS_TYPE,
    NEWS_REF,
    NEWS_FIRSTIMAGE,
    NEWS_SECONDIMAGE,
    NEWS_THIRDIMAGE
    

    
}



// API
export const AUTH_ADMIN = 'AUTH_ADMIN'
export const DESTROY_PAYLOAD = 'DESTROY_PAYLOAD'
